name: build
run-name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
